### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by deadkid14** [fritzr/discord-twitter-bot#10]
i got this error putting my email 

```### Twitter Bot Setup File ###
Enter Discord Email: (my discord email)
Traceback (most recent call last):
  File "/Users/deadpool4/discord-twitter-bot-master/DiscordTwitterBotSetup.py", line 71, in <module>
    main()
  File "/Users/deadpool4/discord-twitter-bot-master/DiscordTwitterBotSetup.py", line 59, in main
    tsetup.osetup()
  File "/Users/deadpool4/discord-twitter-bot-master/DiscordTwitterBotSetup.py", line 25, in osetup
    self.tstorage.dct['d_email'] = input('Enter Discord Email: ')
  File "<string>", line 1
    (my discord email)
             ^
```

**Comment by LeKlex** [comment]
+1

**Comment by fritzr** [comment]
This means you're using Python 2 -- you need to use Python 3.3.
