### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by stepbroshiny** [fritzr/discord-twitter-bot#11]
when running discordtwitterbot.py i just get this error

Traceback (most recent call last):
  File "c:\Users\kp_lo\Desktop\discord-twitter-bot-master\DiscordTwitterBot.py", line 550, in <module>
    main()
  File "c:\Users\kp_lo\Desktop\discord-twitter-bot-master\DiscordTwitterBot.py", line 545, in main    
    t = TwitterBot()
  File "c:\Users\kp_lo\Desktop\discord-twitter-bot-master\DiscordTwitterBot.py", line 290, in __init__
    self.data = Storage()
  File "c:\Users\kp_lo\Desktop\discord-twitter-bot-master\DiscordTwitterBot.py", line 16, in __init__
    with open('data.pkl','rb') as self.tinfo:
FileNotFoundError: [Errno 2] No such file or directory: 'data.pkl'

**Comment by fritzr** [comment]
https://github.com/fritzr/discord-twitter-bot#setup
